URL_SERVICE = "https://cnt-26d9d530-aa71-4cd0-8e24-58d2a4f6e55b.containerhub.tripleten-services.com/"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
